### ISSUE TITLE
Bad dependency on "ansible = 2.2.1.0"

### ISSUE THREAD

**Issue by dahorak** [Tendrl/commons#436] opened 2017-05-05 07:09 UTC
Package `tendrl-commons` from version `1.2.3-05_02_2017_16_12_13` depends on specific version of _ansible_ (previously it depends on `ansible >= 2.2`):
```
# rpm -qRp tendrl-commons-1.2.3-05_02_2017_16_12_13.noarch.rpm
ansible = 2.2.1.0
...
```
I partially understand this change, but we should avoid it and fix it as soon as possible, because it breaks [repoclosure validation](https://ci.centos.org/view/Tendrl/job/tendrl-0-3-package-validation-repoclosure/) and also `yum update`:
```
# repoclosure --newest \
  --repofrompath centos-extras,http://mirror.centos.org/centos/7/extras/x86_64/ \
  --repofrompath fedora-epel,http://mirror.karneval.cz/pub/linux/fedora/epel/7/x86_64/ \
  --repofrompath centos-base,http://mirror.centos.org/centos/7/os/x86_64/ \
  --repofrompath gdeploy,http://copr-be.cloud.fedoraproject.org/results/sac/gdeploy/epel-7-x86_64/ \
  --repofrompath centos-updates,http://mirror.centos.org/centos/7/updates/x86_64/ \
  --repofrompath tendrl-deps,https://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/epel-7-x86_64/ \
  --repofrompath tendrl-core,https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/ \
  --lookaside=centos-extras \
  --lookaside=fedora-epel \
  --lookaside=centos-base \
  --lookaside=gdeploy \
  --lookaside=centos-updates \
  --lookaside=tendrl-deps \
  --repoid=tendrl-core

Added centos-extras repo from http://mirror.centos.org/centos/7/extras/x86_64/
Added fedora-epel repo from http://mirror.karneval.cz/pub/linux/fedora/epel/7/x86_64/
Added centos-base repo from http://mirror.centos.org/centos/7/os/x86_64/
Added gdeploy repo from http://copr-be.cloud.fedoraproject.org/results/sac/gdeploy/epel-7-x86_64/
Added centos-updates repo from http://mirror.centos.org/centos/7/updates/x86_64/
Added tendrl-deps repo from https://copr-be.cloud.fedoraproject.org/results/tendrl/dependencies/epel-7-x86_64/
Added tendrl-core repo from https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/
Reading in repository metadata - please wait....
Checking Dependencies
Repos looked at: 7
   centos-base
   centos-extras
   centos-updates
   fedora-epel
   gdeploy
   tendrl-core
   tendrl-deps
Num Packages in Repos: 20859
package: tendrl-commons-1.2.3-05_05_2017_05_13_07.noarch from tendrl-core
  unresolved deps: 
     ansible = 0:2.2.1.0
```

```
# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.hosting90.cz
 * epel: download.eng.brq.redhat.com
 * extras: mirror.hosting90.cz
 * updates: mirror.hosting90.cz
Resolving Dependencies
--> Running transaction check
---> Package ansible.noarch 0:2.2.1.0-2.el7.centos will be updated
--> Processing Dependency: ansible = 2.2.1.0 for package: tendrl-commons-1.2.3-05_05_2017_05_13_07.noarch
---> Package ansible.noarch 0:2.3.0.0-3.el7 will be an update
--> Finished Dependency Resolution
Error: Package: tendrl-commons-1.2.3-05_05_2017_05_13_07.noarch (@tendrl)
           Requires: ansible = 2.2.1.0
           Removing: ansible-2.2.1.0-2.el7.centos.noarch (@tendrl-dependencies)
               ansible = 2.2.1.0-2.el7.centos
           Updated By: ansible-2.3.0.0-3.el7.noarch (epel)
               ansible = 2.3.0.0-3.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by r0h4n** [comment] 2017-05-05 07:28
What is your suggestion here given the assumption that Tendrl cannot use ansible>2.2.1

**Comment by dahorak** [comment] 2017-05-05 07:43
@r0h4n I'm not sure about the best solution (if there is any). it depends on the reason, why _Tendrl cannot use ansible>2.2.1_
Is it because of code compatibility with tendrl-commons or with some other dependency (e.g. ceph-ansible)?

**Comment by r0h4n** [comment] 2017-05-05 07:48
Ansible>2.2.1 breaks tendrl-commons due to code compatibility reasons (ansible core modules structure has changed etc), we wont be moving beyond ansible>2.2.1 anytime soon.

The solution here would be to not update ansible beyond 2.2.1

**Comment by mkudlej** [comment] 2017-05-05 07:55
@r0h4n  But GDeploy and Ceph-ansible are moving to ansible 2.3. Does it mean, tah we will have 2 Ansible versions in cluster?

**Comment by mbukatov** [comment] 2017-05-05 08:26
> The solution here would be to not update ansible beyond 2.2.1

@r0h4n I understand your point. But for freezing on ansible 2.2.1 to work, we need to make sure that no repository contains more recent ansible rpm build - which is not possible as long as we use epel as  official dependency in upstream tendrl project. Moreover as @mkudlej points out, even if we didn't use epel, ceph-ansible is going towards ansible 2.3 which breaks staying on 2.2.1 as well.

The problem is: what would happen when we require ansible 2.2.1, but there is already more recent ansible installed on a machine? Yum transaction will fail and manual override is needed. Similar problem happens when you have ansible 2.2.1 installed as a dependency of tendrl-commons, but then you run yum update which would try to install more recent build ... this means that any yum transaction will fail on this dependency problem which is hardly acceptable.

This all means that we have no other choice but to update Tendrl to work with more recent ansible versions. Our dependencies doesn't allow for any other solution for both upstream and downstream release.

From your comment, I feel that it would require considerable additional work, so I understand that this will not be done fast - which is fine because it doesn't block most important testing scenarios. But we need to account for this so that we fix this before next upstream release.

**Comment by r0h4n** [comment] 2017-05-05 09:17
@mbukatov I see this dependency pinning causing is more trouble than good. I suggest we move quick on this, i have filed https://github.com/Tendrl/commons/issues/438 

Please run Tendrl on ansible 2.3 when possible and report failures while @GowthamShanmugam also does the same exercise

**Comment by r0h4n** [comment] 2017-05-07 22:11
Fixed

**Closed by r0h4n** 2017-05-07 22:11 UTC
